### ISSUE TITLE
Not able to send data to open weather maps

### ISSUE THREAD

**Issue by kavine** [Benjamin3992/OpenWeatherDuino#1]
I did what you did and i gave my user name and password but the data is not available in the open weather map .

**Comment by kaathi524** [comment]
Where to see the uploaded data in openweathermap ?

**Comment by l0wl3vel** [comment]
The credentials line has to look like this:
#define CredBase64 "TXlVc2VybmFtZTpTZWNyZXRQYXNzd29yZA=="
not like this:
#define CredBase64 "MyUsername:SecretPassword"

you have to encode MyUsername:SecretPassword with a Base64 encoder like this: https://www.base64encode.org/
You can see the data on http://home.openweathermap.org/ in the tab "my weather stations"
